### Site info.
title: DBA@Robin
tagline: Focus on database.
author: Robin Wen
email: dbarobinwen@gmail.com 
description: Robin Wen, MySQL DBA, Liberalist. Record every step about my fighting. Above all, do not lose hope.
keywords: "MySQL, Linux, Python, Reading, DBA, Muisc, 阅读, 音乐, 钢琴, 文学"
url: "http://dbarobin.com" # The base hostname & protocol for your site
locale: en_US

### Personal info and site tools info.
twitter_username: dbarobin
github_username:  dbarobin
disqus_shortname: dbarobin
favicon:     "/images/favicon.ico"
aboutme: Robin Wen, MySQL DBA.
aboutme_photo: "/images/wentasy.png"
google_analytics_key: UA-57297247-1

### Site settings.
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True.
default_column: "two" # Blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # Blog sidebar language set, only include: English(en) and Chinese (cn).

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Google_Search: "Google Search"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
      WechatDBTalk: "WeChat Official Account"
      WechatDonate: "Donate"
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "Blogroll"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Google_Search: "搜索"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      WechatDBTalk: "微信公众号"
      WechatDonate: "微信捐赠"


### Blogroll info, only name can shown on the page.
Blogroll:
    - name: DBA@DevOps
      href: http://blog.csdn.net/dba_waterbin
      title: DBA@DevOps

### Build settings.
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: pygments
paginate: 5
excerpt_separator: <!--more-->

### Kramdown settings.
kramdown:
  input: GFM 
  hard_wrap: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

### Custom gems.
